### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by ChristianNSchmitz** [jackgoffinet/autoencoded-vocal-analysis#1]
Dear AVA-Team,

we are trying to run the code on rodent vocalization but have following issue. The error indicates that noverlap must be less than nperseg, however, this is already correctly defined in the beginning.
We would highly appreciate your support.

Best,
Christian

```
>>> seg_params = tune_segmenting_params(audio_directories, seg_params)
Tune segmenting parameters

Set value for min_freq: [30000.0]
Set value for max_freq: [110000.0]
Set value for nperseg: [1024]
Set value for noverlap: [512]
Set value for spec_min_val: [2.0]
Set value for spec_max_val: [6.0]
Set value for fs: [250000] 192000
Set value for th_1: [1.5]
Set value for th_2: [2.0]
Set value for th_3: [2.5]
Set value for min_dur: [0.03]
Set value for max_dur: [0.2]
Set value for smoothing_timescale: [0.007]
Set value for temperature: [0.5]
/usr/local/lib/python3.8/dist-packages/scipy/signal/spectral.py:1961: UserWarning: nperseg = 1024 is greater than input length  = 2, using nperseg = 2
  warnings.warn('nperseg = {0:d} is greater than input length '
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/ava/segmenting/segment.py", line 132, in tune_segmenting_params
    spec, dt, f = get_spec(audio, p)
  File "/usr/local/lib/python3.8/dist-packages/ava/segmenting/utils.py", line 44, in get_spec
    f, t, spec = stft(audio, fs=p['fs'], nperseg=p['nperseg'], \
  File "/usr/local/lib/python3.8/dist-packages/scipy/signal/spectral.py", line 1169, in stft
    freqs, time, Zxx = _spectral_helper(x, x, fs, window, nperseg, noverlap,
  File "/usr/local/lib/python3.8/dist-packages/scipy/signal/spectral.py", line 1754, in _spectral_helper
    raise ValueError('noverlap must be less than nperseg.')
ValueError: noverlap must be less than nperseg.

```

**Comment by jackgoffinet** [comment]
Hi Christian, thanks for opening an issue. There's a chance this is fixed in the dev branch, which I'm planning on merging soon. If you navigate to the ``autoencoded-vocal-analysis`` directory in a shell and enter ``git log -1``, what is the output?

**Comment by jackgoffinet** [comment]
Hi @ChristianNSchmitz , I merged these changes into the master branch yesterday. I think there's a fix in this newer version, but feel free to reopen the issue you get the same error and I'll take a closer look.
